CREATE TABLE "HR_APP"."PROFILES"
(	"ID" NUMBER,
     "NAME" VARCHAR2(50 BYTE),
     "DESTINATION" VARCHAR2(50 BYTE),
     "EMAIL" VARCHAR2(100 BYTE),
     "GENDER" VARCHAR2(30 BYTE),
     "STAFF_ID" NUMBER,
     "USER_ID" NUMBER,
     "IMAGE" VARCHAR2(255 BYTE),
     "PHONE" VARCHAR2(9 BYTE),
     "ADDRESS" VARCHAR2(150 BYTE)
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;