CREATE TABLE "HR_APP"."REQUESTS_TIME_OFF"
(	"ID" NUMBER DEFAULT "HR_APP"."INCREMENT_REQUEST"."NEXTVAL",
     "LEAVE_TYPE" VARCHAR2(255 BYTE),
     "REASON" VARCHAR2(255 BYTE),
     "START_DATE" DATE,
     "END_DATE" DATE,
     "STATUS" VARCHAR2(50 BYTE),
     "EMPLOYEE_ID" NUMBER
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;