CREATE TABLE "HR_APP"."TASKS"
(	"ID" NUMBER DEFAULT "HR_APP"."INCREMENT_TASK"."NEXTVAL",
     "NAME" VARCHAR2(50 BYTE),
     "STATUS" VARCHAR2(30 BYTE),
     "ESTIMATED_TASK_TIME_END" DATE,
     "ESTIMATED_WORK_TIME" DATE,
     "PRIORITY_STATUS" VARCHAR2(30 BYTE),
     "START_DATE" DATE,
     "TYPE_TASK" VARCHAR2(30 BYTE),
     "PROJECT_ID" NUMBER,
     "EMPLOYEE_ID" NUMBER
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;